const products = [
	{
		type: 'electronics',
		name: 'Audio Technica ATH-M50x',
		price: 119.99,
		quantity: 2
	},
	{
		type: 'electronics',
		name: 'Sennheiser HD 202 II',
		price: 24.50,
		quantity: 5
	},
	{
		type: 'electronics',
		name: 'GPX HM3817DTBK Micro System',
		price: 135.99,
		quantity: 1
	},
	{
		type: 'electronics',
		name: 'Samsung MX-J630 2.0 Channel 230 Watt System',
		price: 117.99,
		quantity: 4
	},
	{
		type: 'electronics',
		name: 'M-Audio Bass Traveler',
		price: 29.00,
		quantity: 9
	},
	{
		type: 'electronics',
		name: 'HLED Strip light kit',
		price: 17.95,
		quantity: 5
	},
	{
		type: 'movies',
		name: 'Spectre',
		price: '19.99',
		quantity: 0
	},
	{
		type: 'movies',
		name: 'Finding Dory',
		price: 19.99,
		quantity: 4
	},
	
	{
		type: 'movies',
		name: 'Terminator: Genisys',
		price: 14.95,
		quantity: 3
	},
	{
		type: 'movies',
		name: 'Interstellar',
		price: 12.00,
		quantity: 4
	},
	{
		type: 'movies',
		name: 'Transformers: Age of Extinction',
		price: 9.95,
		quantity: 7
	},
	{
		type: 'movies',
		name: 'Eye in the Sky',
		price: 14.95,
		quantity: 6
	},
	{
		type: 'movies',	
		name: 'Venom',
		price: '22.99',
		quantity: 0
	},
	{
		type: 'movies',
		name: 'The spy who dumped me',
		price: 29.00,
		quantity: 8
	},
	{
		type: 'movies',
		name: 'Mamma Mia, Here We Go Again',
		price: 22.99,
		quantity: 4
	},
	{
		type: 'electronics',
		name: 'M-Audio Bass Traveler',
		price: 29.00,
		quantity: 5
	},
	{
		type: 'video-games',
		name: 'Battlefield 1',
		price: 59.99,
		quantity: 3
	},
	{
		type: 'video-games',
		name: 'Overwatch',
		price: 40.00,
		quantity: 1
	},
	{
		type: 'video-games',
		name: 'Gears of War 4',
		price: 59.99,
		quantity: 8
	},
	{
		type: 'video-games',
		name: 'Titanfall 2',
		price: 59.99,
		quantity: 7
	},
	{
		type: 'video-games',
		name: 'Sid Meier\'s Civilization VI ',
		price: 59.99,
		quantity: 4
	},
	{
		type: 'video-games',
		name: 'The Sims 4',
		price: 39.99,
		quantity: 2
	},
	{
		type: 'video-games',
		name: 'Grand Theft Auto V',
		price: 59.99,
		quantity: 7
	}
];

function displayProductList() {
	console.log("1. Display name, type, and price of each product.\n");
	let task1 = "";
	const max = products.length;
	for(let i = 0; i < max; i++) {
		const p = products[i];
		task1 += "Name: " + p.name + "\n";
		task1 += "Type: " + p.type + "\n";
		task1 += "Price: " + p.price + "\n\n";
	}
	console.log(task1);

	console.log("2. Display name, type, and price of each product with a price greater than 50.\n");
	let task2 = "";
	for(let j = 0; j < max; j++) {
		const p = products[j];
		if(p.price > 50){
			task2 += "Name: " + p.name + "\n";
			task2 += "Type: " + p.type + "\n";
			task2 += "Price: " + p.price + "\n\n";
		}
	}
	console.log(task2);

	console.log("3. Display name, type, and price of each electronic item with a price greater than 50.\n");
	let task3 = "";
	for(let k = 0; k < max; k++) {
		const p = products[k];
		if(p.type == "electronics" && p.price > 50) {
			task3 += "Name: " + p.name + "\n";
			task3 += "Type: " + p.type + "\n";
			task3 += "Price: " + p.price + "\n\n";
		}
	}
	console.log(task3);

	console.log("4. Revenue generated by each product is calculated by multiplying price and quantity: \n\trevenue = price * quantity. \n\tDisplay the revenue generated by each item (display name, price, quantity, revenue).\n");
	let task4 = "";
	for(let l = 0; l < max; l++) {
		const p = products[l];
		let revenue = parseFloat(p.price) * parseFloat(p.quantity);
		task4 += "Name: " + p.name + "\n";
		task4 += "Price: " + p.price + "\n";
		task4 += "Quantity: " + p.quantity + "\n";
		task4 += "Revenue: $" + revenue.toFixed(2) + "\n\n";
	}
	console.log(task4);

	console.log("5. Display the total revenue.\n");
	let task5 = "";
	let totalRevenue = 0;
	for(let m = 0; m < max; m++) {
		const p = products[m];
		let revenue = parseFloat(p.price) * parseFloat(p.quantity);
		totalRevenue += revenue;
		task5 = "Total Revenue: $" + totalRevenue.toFixed(2) + "\n\n";
	}
	console.log(task5);

	console.log("6. Find the revenue generated by electronic items (display name, type, price, quantity, revenue).\n");
	let task6 = "";
	for(let n = 0; n < max; n++) {
		const p = products[n];
		if(p.type == "electronics") {
			let revenue = parseFloat(p.price) * parseFloat(p.quantity);
			task6 += "Name: " + p.name + "\n";
			task6 += "Type: " + p.type + "\n";
			task6 += "Price: " + p.price + "\n";
			task6 += "Quantity: " + p.quantity + "\n";
			task6 += "Revenue: $" + revenue.toFixed(2) + "\n\n";
		}
	}
	console.log(task6);
}

displayProductList();